apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-svc
  name: redis-svc
  namespace: share-app
spec:
  ports:
    - port: 6379
      name: http-6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31111
  selector:
    app: redis-server
  type: NodePort