apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: share-app
  name: redis-server
  labels:
    app: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
        - name: redis-server
          image: redis:5.0.14
          ports:
            -  containerPort: 6739
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: conf
              mountPath: /usr/local/etc/redis/redis.conf
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "redis-cli config set requirepass 123456"]
      volumes:
        - name: conf
          hostPath:
            path: /home/redis/redis.conf
            type: DirectoryOrCreate