server:
  port: 9001

line:
  server:
    host: 127.0.0.1
    port: 9000
    path: /ws/conn
  reconnect:
    count: 3


spring:
  redis:
    host: 192.168.1.61
    port: 31111
    database: 1
  data:
    mongodb:
      host: 192.168.1.61
      port: 31110
      database: lucas
      authentication-database: lucas
      username: admin
      password: "123456"

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      database: ${spring.redis.database}

logging:
  level:
    web: DEBUG

