server:
  port: 9001

line:
  server:
    host: 127.0.0.1
    port: 9000
    path: /ws/conn
  reconnect:
    count: 3


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://62.234.42.130:9901/share-im?useSSL=false&serverTimezone=UTC
    username: root
    password: 8af14495be1e271841b5c2975d9f5689
    hikari:
      pool-name: share-rbac-pool
  redis:
    host: 62.234.42.130
    port: 9902
    database: 1
    password: 8af14495be1e271841b5c2975d9f5689
  data:
    mongodb:
      host: 62.234.42.130
      port: 9900
      database: share-im-store
      authentication-database: admin
      username: lucas
      password: "8af14495be1e271841b5c2975d9f5689"

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      database: ${spring.redis.database}

logging:
  level:
    web: DEBUG

mybatis-plus:
  mapperLocations: classpath*:/mybatis/mapper/*.xml

share:
  info: share-cloud
  jwt:
    secret: share-andot
    expiration: 7200
  video:
    folder: /Users/lucasser/Andot/App/ffmpeg/video/
