server:
  port: 9901
  servlet:
    context-path: /api

line:
  server:
    host: 127.0.0.1
    port: 9900
    path: /ws/conn
  reconnect:
    count: 3


spring:
  redis:
    host: 127.0.0.1
    database: 1

logging:
  level:
    web: DEBUG

