server:
  port: 9001

line:
  server:
    host: 127.0.0.1
    port: 9000
    path: /ws/conn
  reconnect:
    count: 3


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.3:3306/share-im?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: share-rbac-pool
  redis:
    host: 114.113.230.69
    port: 16379
    database: 1
    password: Enst@2022
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: share-im-store
      authentication-database: admin
      username: admin
      password: "123456"

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      database: ${spring.redis.database}

logging:
  level:
    web: DEBUG

mybatis-plus:
  mapperLocations: classpath*:/mybatis/mapper/*.xml

share:
  info: share-cloud
  jwt:
    secret: share-andot
    expiration: 7200
  video:
    folder: /Users/lucasser/Andot/App/ffmpeg/video/
