apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: share-app
  name: share-app-im
  labels:
    app: share-app-im
spec:
  selector:
    matchLabels:
      app: share-app-im
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: share-app-im
    spec:
      containers:
        - name: share-app-im
          image: harbor.andot.org/lucas/share-app-im:1.0.0
          ports:
            -  containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "500m"
              memory: "512Mi"