server:
  port: 9090
  servlet:
    context-path: /api

spring:
  application:
    name: share-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/share-rbac?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: share-rbac-pool


share:
  info: share-cloud
  jwt:
    secret: share-andot
    expiration: 7200