server:
  port: 8090

spring:
  application:
    name: share-api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/share-rbac?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: matengfei
    password: Matengfei$1991
    hikari:
      pool-name: share-rbac-pool
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6377
    sentinel:
      master: redis-sentinel-master
      nodes:
        - 127.0.0.1:6377
      password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
    host: 127.0.0.1
    port: 6379
  logging:
    level:
      com.baomidou.mybatisplus.samples.quickstart: debug

mybatis-plus:
  mapperLocations: classpath*:/mybatis/mapper/*.xml

share:
  info: share-cloud
  jwt:
    secret: share-andot
    expiration: 7200