apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-gateway
  name: nginx-gateway
  namespace: ns-nginx
spec:
  ports:
    - port: 9000
      name: nginx-service80
      protocol: TCP
      targetPort: 80
      nodePort: 31090
  selector:
    app: nginx-gateway
  type: NodePort