apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: share-app
  name: mongo-server
  labels:
    app: mongo-server
spec:
  selector:
    matchLabels:
      app: mongo-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
        - name: mongo-server
          image: mongo:5.0.9
          ports:
            -  containerPort: 27017
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          hostPath:
            path: /home/mongo/data/
            type: DirectoryOrCreate