apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-svc
  name: mongo-svc
  namespace: share-app
spec:
  ports:
    - port: 27017
      name: http-27017
      protocol: TCP
      targetPort: 27017
      nodePort: 31110
  selector:
    app: mongo-server
  type: NodePort